version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api     # novo Dockerfile separado da API
    container_name: astel-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=astelsp1_Astel.sqlserver.dbaas.com.br;Database=astelsp1_Astel;User Id=astelsp1_Astel;Password=Astel@5691;TrustServerCertificate=True;
    restart: unless-stopped

